import { proof } from "../proof";
import type { MctCopy } from "./copy";
import { policies } from "./policies";

export const en = {
  meta: {
    hub: {
      title: "Microsoft Fabric, Copilot & Azure SQL training for teams | Ludwik C. Siadlak",
      description: `Live online Microsoft training for teams of 3–30, executive briefings and custom enterprise programs. Fabric, Copilot, Azure SQL. Max 8 per class. Microsoft Certified Trainer for ${proof.yearsMct} years.`,
    },
    briefing: {
      title: "Executive briefing: Copilot, Fabric, AI governance | Ludwik C. Siadlak",
      description:
        "Three hours, up to 10 leaders, one decision unblocked. Copilot ROI, Fabric build vs buy, or AI governance for regulated organisations.",
    },
    enterprise: {
      title: "Custom Microsoft training programs for enterprise | Ludwik C. Siadlak",
      description:
        "Programs written for your stack, your rollout and your deadline. Private runs of any course, remote or on-site, English or Polish. NDA, PO and vendor onboarding handled.",
    },
    course: {
      title: "{title} | Live online training | Ludwik C. Siadlak",
      description: "{tagline}",
    },
  },
  nav: {
    brand: "Ludwik C. Siadlak",
    hub: "Training",
    courses: "Courses",
    briefing: "Executive briefing",
    enterprise: "Enterprise",
    request: "Request",
    localeSwitch: "Polska wersja",
  },
  hero: {
    eyebrow: `Microsoft Certified Trainer · ${proof.yearsMct} years · ${proof.trainedProfessionals} professionals trained`,
    line1: "BATTLE-TESTED,",
    line2: "NOT LAB-TESTED.",
    sub: "Microsoft Fabric, Copilot and Azure SQL training from the trainer Fortune 500 and NATO booked. Public online classes for small teams. Custom programs for enterprise. Same courseware standard either way.",
    pathTeams: "For teams of 3–30",
    pathEnterprise: "For enterprise & public sector",
    nextClass: "Next public class: {course}, {date}",
  },
  trust: { eyebrow: "Teams I have trained" },
  segment: {
    teams: {
      title: "Teams of 3–30.",
      body: "Pick a course, pick a date, request seats. {price} net per training day. Max 8 people per class, so you get answers, not a webinar. Invoice, not a checkout.",
      cta: "See dates and prices",
    },
    enterprise: {
      title: "Enterprise & public sector.",
      body: "A program written for your stack, your rollout, your deadline. Private runs of any course. NDA, PO and vendor onboarding handled. 20-minute scope call, no pitch.",
      cta: "How custom programs work",
    },
  },
  tiers: {
    eyebrow: "Three ways to work with me",
    title: "Pick the format that fits the problem.",
    briefingBadge: "For leadership",
    footnote: "Six or more? A private run is usually the better deal.",
    items: {
      public: {
        title: "Public online class, per seat",
        price: "{perDay} / day · 2-day {twoDay} (net)",
        bullets: [
          "Live online, max 8",
          "Hands-on labs on your own environment",
          "3+ seats −10%",
          "Materials + 30 days of follow-up Q&A by email",
        ],
        cta: "Request a seat",
      },
      briefing: {
        title: "Half-day executive briefing",
        price: "{flat} flat (net)",
        bullets: ["3 hours, remote", "Up to 10 leaders", "One topic, your numbers on the table", "Written summary within 48 h"],
        cta: "Book a briefing",
      },
      enterprise: {
        title: "Custom enterprise program",
        price: "Quoted per program",
        bullets: [
          "Private run of any course",
          "Custom courseware for your stack",
          "Remote or on-site, EN/PL",
          "Multi-cohort, NDA, PO, vendor onboarding",
        ],
        cta: "Scope it in 20 minutes",
      },
    },
  },
  schedule: {
    eyebrow: "Upcoming public classes",
    title: "Fixed dates, small classes.",
    columns: { course: "Course", dates: "Dates", hours: "Hours", language: "Language", status: "Status", action: "" },
    hoursValue: "09:00–17:00 CET/CEST",
    status: {
      open: "Open",
      filling: "Filling",
      full: "Full",
      confirmed: "Confirmed to run",
      cancelled: "Cancelled",
    },
    languages: { en: "English", pl: "Polish" },
    seatsLeft: "{n} seats left",
    rowCta: "Request a seat",
    empty: {
      title: "First public dates are being set for Q4 2026.",
      body: "Tell me which course and I'll notify you first, or request a private run.",
      notify: "Notify me",
      privateRun: "Request a private run",
    },
  },
  catalog: {
    eyebrow: "Phase-1 catalog",
    title: "Three tracks, one courseware standard.",
    footer:
      "Power BI, Microsoft 365 and Data Engineering tracks follow. Need one now? Ask, it is probably a private run away.",
    dayOne: "1 day",
    dayMany: "{n} days",
    cardCta: "See the course",
  },
  badges: {
    condensed: "Condensed 2-day",
    official: "Official Microsoft course",
    custom: "Ludwik's courseware",
  },
  levels: { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" },
  whyMe: {
    eyebrow: "Why me",
    title: "Most trainers read the courseware. I have written it.",
    headers: { them: "Most Microsoft trainers", me: "Ludwik" },
    rows: [
      { them: "Read the official courseware", me: "Wrote custom training programs for NATO" },
      { them: "Teach features", me: "Teaches systems that survive production" },
      {
        them: "Know the current version",
        me: `Trained every generation of the Microsoft data stack for ${proof.yearsMct} years`,
      },
      { them: "Deliver in a lab", me: "Has consulted for Fortune 500 and military organisations" },
      {
        them: "Speak one language to one audience",
        me: "Switches between deep T-SQL and C-level strategy in the same day",
      },
    ],
  },
  proof: {
    eyebrow: "From evaluation forms",
    title: "{n} evaluation-form quotes. Zero scripted.",
    sub: "Every quote comes from a post-training evaluation form. No stars, because I do not have a scored dataset yet; when I do, you will see the number and the sample size.",
    note: "Originals in English.",
    filters: {
      all: "All",
      military: "Military",
      enterprise: "Enterprise",
      data: "Data",
      modernwork: "Modern Work",
    },
    readAll: "Read all {n}",
    showFewer: "Show fewer",
    empty: "No quotes under this filter yet.",
  },
  process: {
    eyebrow: "How it works",
    title: "What happens after you click.",
    lanes: {
      public: {
        title: "Public seats",
        beats: [
          "Request seats (2 min)",
          "I confirm the date and send a pro-forma or invoice within 1 business day",
          "Pre-course check: lab access, prerequisites, your questions",
          "Class, materials, 30 days of follow-up Q&A",
        ],
      },
      briefing: {
        title: "Briefing",
        beats: [
          "Pick a topic and 2–3 time windows",
          "I confirm a slot and send a one-page prep note",
          "3 hours, your numbers on the table",
          "Written summary within 48 h",
        ],
      },
      enterprise: {
        title: "Enterprise",
        beats: [
          "Tell me your stack & timeline (2 min)",
          "20-minute scope call, no pitch",
          "A program built around you",
          "Delivery that sticks: remote or on-site, EN or PL",
        ],
      },
    },
  },
  faq: { eyebrow: "FAQ", title: "Questions buyers ask before they book." },
  finalCta: {
    title: "Your next training should change what your team ships.",
    sub: "Pick a seat, book a briefing, or scope a program. I answer within one business day, and if I am not the right fit I will say so.",
    contactLine: "Prefer email? {email}",
  },
  footer: {
    since: "Microsoft Certified Trainer since 2007",
    catalog: "Courses",
    formats: "Ways to work together",
    contact: "Contact",
    responseTime: "Reply within one business day.",
    privacy: "Privacy policy",
  },
  form: {
    eyebrow: "Request",
    modes: { seat: "Public seats", briefing: "Briefing", scope: "Custom program" },
    titles: { seat: "Request seats", briefing: "Request a briefing", scope: "Scope a program" },
    labels: {
      name: "Name",
      email: "Work email",
      company: "Company",
      phone: "Phone (optional)",
      course: "Course",
      session: "Date",
      sessionNotify: "Notify me about the next date",
      seats: "Seats",
      language: "Delivery language",
      topic: "Topic",
      windows: "Preferred time windows (2–3)",
      leaders: "Number of leaders",
      stack: "Stack",
      teamSize: "Team size and roles",
      timeline: "Timeline",
      delivery: "Delivery",
      procurement: "Procurement constraints",
      message: "Notes",
      consent: "I agree to be contacted about this request. Privacy policy applies.",
      wantsPrivateQuote: "Also quote a private run",
    },
    placeholders: {
      briefingMessage: "What decision should this briefing unblock?",
      windows: "e.g. Tuesday morning, Thursday after 14:00",
      teamSize: "e.g. 12 people: 8 analysts, 4 engineers",
      timeline: "e.g. Fabric go-live next quarter",
      procurement: "PO, NDA, vendor portal, payment terms…",
      message: "Anything I should know before I reply?",
    },
    options: {
      topicCustom: "My own question",
      stack: {
        copilot: "Copilot & AI",
        fabric: "Microsoft Fabric",
        sql: "Azure SQL",
        powerbi: "Power BI",
        m365: "Microsoft 365",
        other: "Other",
      },
      delivery: { remote: "Remote", onsite: "On-site", hybrid: "Hybrid" },
      languages: { en: "English", pl: "Polish" },
    },
    quote: {
      line: "{n} × {price}",
      discount: "Multi-seat discount −{percent}%",
      total: "Total, net",
      addSeat: "Add a seat",
      removeSeat: "Remove a seat",
    },
    submit: { seat: "Request seat(s)", briefing: "Request a briefing", scope: "Send and pick a call slot" },
    sending: "Sending…",
    microcopy: {
      seat: "No payment now. You get a confirmation within one business day and an invoice or pro-forma once the date is confirmed.",
    },
    seatsHint6: "Six or more? A private run may be cheaper — tick to get both quotes.",
    success: {
      title: "Got it.",
      body: {
        seat: "Once your date is confirmed I send the invoice or pro-forma and the pre-course checklist.",
        briefing: "I will propose a slot from your windows and send a one-page prep note.",
        scope: "Pick a 20-minute slot below, or wait for my email with three questions that make the call useful.",
      },
      calendar: "Pick a 20-minute slot",
    },
    error: "Something went wrong. Your answers are still here — try again or email {email}.",
    errors: {
      required: "This field is required.",
      email: "Enter a valid work email.",
      consent: "Please confirm you agree to be contacted.",
    },
  },
  sticky: {
    teams: { label: "Seats from {perDay} net", cta: "Request a seat" },
    enterprise: { label: "Rolling out Fabric or Copilot?", cta: "Scope it in 20 minutes" },
    course: { label: "{code} · next date {date}", cta: "Request a seat" },
    courseNoDate: { label: "{code}", cta: "Request a private run" },
    briefing: { label: "3 hours, 10 leaders, {flat} net", cta: "Book a briefing" },
    enterprisePage: { label: "20-minute scope call, no pitch", cta: "Pick a time" },
    dismiss: "Dismiss",
  },
  course: {
    duration: "Duration",
    level: "Level",
    maxSeats: "Max 8",
    liveOnline: "Live online",
    perSeat: "per seat",
    orPrivate: "or a private run for your team",
    condensedNotice:
      "Condensed 2-day format. We cover the exam-relevant core of the official outline at a fast pace. Need every module? Ask for a private run on the full schedule.",
    audience: "Who it's for",
    notFor: "Not for",
    outcomesOne: "After one day your team can:",
    outcomes: "After {n} days your team can:",
    agenda: "Agenda",
    day: "Day {n}",
    addOn: "Ludwik's add-on",
    prerequisites: "Prerequisites",
    msLearn: "Official outline on Microsoft Learn",
    exam: "Exam {code}",
    format: {
      title: "Format",
      items: [
        "Live online, 09:00–17:00 CET/CEST",
        "Max 8 participants",
        "Hands-on labs on your own environment",
        "Deck and lab files to keep",
        "30 days of follow-up Q&A by email",
      ],
      recording: policies.recording.en,
    },
    datesTitle: "Dates for this course",
    trainer: {
      eyebrow: "Your trainer",
      name: "Ludwik C. Siadlak",
      years: "years as MCT",
      trained: "professionals trained",
      countries: "countries",
    },
    related: "Related courses",
  },
  briefing: {
    eyebrow: "Executive briefing",
    title: "Three hours. One decision unblocked.",
    sub: "{flat} net. 3 hours remote, up to 10 leaders, written summary in 48 h.",
    cta: "Book a briefing",
    topicsEyebrow: "Pick one topic",
    topicsTitle: "Three topics. One decision each.",
    outcomesLabel: "You leave with",
    agendaLabel: "3-hour agenda",
    topics: {
      a: {
        title: "Copilot ROI reality check",
        outcomes: [
          "Know which workflows Copilot moves and which it does not",
          "A licensing decision you can defend",
          "A 90-day pilot design with metrics",
        ],
        agenda: [
          { time: "0:00–0:30", item: "What Copilot actually does across M365 (live, not slides)" },
          { time: "0:30–1:15", item: "Your five candidate workflows, scored on time saved vs risk" },
          { time: "1:15–1:30", item: "Break" },
          {
            time: "1:30–2:15",
            item: "Licensing, data exposure and governance prerequisites (sensitivity labels, oversharing)",
          },
          { time: "2:15–2:45", item: "Pilot design: cohort, metrics, exit criteria" },
          { time: "2:45–3:00", item: "Decisions and owners" },
        ],
      },
      b: {
        title: "Fabric: build vs buy for your data estate",
        outcomes: [
          "A clear position on Fabric vs your current stack (Synapse, Databricks, Snowflake, on-prem SQL)",
          "A capacity and cost model",
          "A migration sequence",
        ],
        agenda: [
          { time: "0:00–0:20", item: "Your current estate on one slide (yours)" },
          { time: "0:20–1:00", item: "Fabric architecture in 40 minutes" },
          { time: "1:00–1:45", item: "Capacity model and F-SKU cost at your volumes" },
          { time: "1:45–2:25", item: "What to move first, what never to move" },
          { time: "2:25–2:45", item: "Skills gap and training sequence" },
          { time: "2:45–3:00", item: "Decisions" },
        ],
      },
      c: {
        title: "AI governance for regulated organisations",
        outcomes: [
          "A governance posture that satisfies audit without freezing adoption",
          "A decision on data boundaries",
          "A responsible-AI checklist owned by named people",
        ],
        agenda: [
          { time: "0:00–0:30", item: "Threat model for generative AI in your context" },
          { time: "0:30–1:15", item: "Microsoft's controls: Purview, DLP, tenant grounding, agent governance" },
          { time: "1:15–1:45", item: "Policy skeleton" },
          { time: "1:45–2:15", item: "Incident playbook" },
          { time: "2:15–2:45", item: "Approval workflow for new agents" },
          { time: "2:45–3:00", item: "Decisions" },
        ],
      },
    },
    ownQuestion: "Bring your own question. Same format, same price.",
  },
  enterprise: {
    eyebrow: "Enterprise & public sector",
    title: "Custom programs for your stack, your rollout, your deadline.",
    sub: "Not a public course with your logo on the slides. I start from your stack, your rollout date and the roles in the room, then assemble from official Microsoft courseware, my own courseware and your systems. Delivery is one cohort or twelve, remote or on-site, English or Polish. You get a program document before you get an invoice.",
    primaryCta: "Scope it in 20 minutes",
    secondaryCta: "Pick a call slot",
    casesEyebrow: "Where this has run",
    casesTitle: "Rooms I have trained in.",
    cases: [
      { title: "NATO", body: "Custom training programs, written not read." },
      { title: "US Army Europe / USARAF", body: "Week-long technical courses, Wiesbaden and Vicenza." },
      { title: "Nordea, ING, DNB", body: "Data platform training for banking teams." },
      { title: "Volvo, Scania, Volkswagen", body: "Manufacturing data teams." },
    ],
    procurement: {
      eyebrow: "Procurement",
      title: "The paperwork is on me.",
      facts: [
        {
          label: "VAT",
          body: "Prices are net. EU companies with a valid VAT ID: reverse charge. Polish companies: +23% VAT.",
        },
        { label: "Purchase orders", body: "Send the PO number and it goes on the invoice." },
        { label: "NDA", body: "Yours or mine, signed before the scope call if you need it." },
        { label: "Vendor onboarding", body: "I fill in your supplier forms. You send them." },
        { label: "Payment terms", body: policies.paymentTerms.en },
        { label: "Cancellation", body: policies.cancellationPrivate.en },
      ],
    },
    privateRun: {
      title: "Private runs",
      body: "Private runs are quoted per training day, not per head. For a full team that is usually the better deal, and I show you both numbers side by side.",
    },
  },
} satisfies MctCopy;
