import { proof } from "../proof";
import type { MctCopy } from "./copy";
import { policies } from "./policies";

export const pl = {
  meta: {
    hub: {
      title: "Szkolenia Microsoft: Fabric, Copilot, SQL",
      description: `Szkolenia online na żywo z Fabric, Copilota i Azure SQL. Maks. 8 osób w klasie, briefingi i programy na zamówienie. Microsoft Certified Trainer od ${proof.yearsMct} lat.`,
      keywords:
        "szkolenia Microsoft Fabric, szkolenia Copilot, szkolenia Azure SQL, DP-600, Microsoft Certified Trainer, szkolenie online na żywo, szkolenia dla zespołów",
    },
    briefing: {
      title: "Briefing dla zarządu: Copilot, Fabric, AI",
      description:
        "Trzy godziny, do 10 osób z zarządu, jedna decyzja odblokowana. ROI Copilota, Fabric: budować czy kupować, albo governance AI w organizacji regulowanej.",
      keywords:
        "briefing dla zarządu, ROI Copilota, strategia Microsoft Fabric, governance AI, strategia AI dla liderów, warsztat dla zarządu, Microsoft Certified Trainer",
    },
    enterprise: {
      title: "Szkolenia Microsoft dla enterprise",
      description:
        "Programy pod Twój stack, wdrożenie i termin. Prywatne edycje kursów, zdalnie lub on-site, po polsku lub angielsku. NDA i formalności zakupowe po mojej stronie.",
      keywords:
        "szkolenia Microsoft dla firm, program szkoleniowy na zamówienie, szkolenie zamknięte, szkolenie on-site, wdrożenie Copilota, szkolenia Microsoft Fabric, Microsoft Certified Trainer",
    },
    course: {
      title: "{shortTitle}",
      description:
        "{tagline} {days}-dniowa klasa online na żywo, maks. 8 miejsc, od {price} za miejsce (netto).",
      keywords:
        "{code}, szkolenie Microsoft, kurs online na żywo, szkolenie z trenerem, szkolenie w małej grupie, szkolenia dla zespołów, Microsoft Certified Trainer",
    },
  },
  nav: {
    brand: "Ludwik C. Siadlak",
    hub: "Szkolenia",
    courses: "Kursy",
    briefing: "Briefing dla zarządu",
    enterprise: "Enterprise",
    request: "Zapytaj",
    localeSwitch: "English version",
    ariaLabel: "Główna",
    localeSwitchLabel: "Przełącz na angielski",
  },
  hero: {
    eyebrow: `Microsoft Certified Trainer · ${proof.yearsMct} lat · ${proof.trainedProfessionals} przeszkolonych`,
    line1: "SPRAWDZONE W BOJU,",
    line2: "NIE W LABIE.",
    sub: "Szkolenia z Microsoft Fabric, Copilota i Azure SQL od trenera, którego zatrudniały Fortune 500 i NATO. Otwarte klasy online dla małych zespołów. Programy na zamówienie dla enterprise. Ten sam standard w obu wariantach.",
    pathTeams: "Dla zespołów 3–30 osób",
    pathEnterprise: "Dla enterprise i sektora publicznego",
    nextClass: "Najbliższa otwarta klasa: {course}, {date}",
  },
  trust: { eyebrow: "Zespoły, które szkoliłem" },
  segment: {
    teams: {
      title: "Zespoły 3–30 osób.",
      body: "Wybierasz kurs, termin, liczbę miejsc. {price} netto za dzień szkoleniowy. Maks. 8 osób w klasie, więc dostajesz odpowiedzi, nie webinar. Faktura, nie koszyk.",
      cta: "Zobacz terminy i ceny",
    },
    enterprise: {
      title: "Enterprise i sektor publiczny.",
      body: "Program napisany pod Twój stack, Twoje wdrożenie, Twój termin. Prywatne edycje dowolnego kursu. NDA, zamówienie, onboarding dostawcy: załatwione. 20-minutowa rozmowa o zakresie, bez pitchu.",
      cta: "Jak działają programy na zamówienie",
    },
  },
  tiers: {
    eyebrow: "Trzy sposoby współpracy",
    title: "Format dobierasz do problemu.",
    briefingBadge: "Dla zarządu",
    footnote: "Sześć osób lub więcej? Prywatna edycja zwykle wychodzi lepiej.",
    items: {
      public: {
        title: "Otwarta klasa online, za miejsce",
        price: "{perDay} / dzień · 2 dni {twoDay} (netto)",
        bullets: [
          "Na żywo online, maks. 8 osób",
          "Ćwiczenia praktyczne (laby) w Twoim środowisku",
          "Od 3 miejsc −10%",
          "Materiały + 30 dni pytań mailem po szkoleniu",
        ],
        cta: "Zarezerwuj miejsce",
      },
      briefing: {
        title: "Półdniowy briefing dla zarządu",
        price: "{flat} ryczałt (netto)",
        bullets: ["3 godziny, zdalnie", "Do 10 osób z zarządu", "Jeden temat, Twoje liczby na stole", "Pisemne podsumowanie w 48 h"],
        cta: "Zamów briefing",
      },
      enterprise: {
        title: "Program enterprise na zamówienie",
        price: "Wycena indywidualna",
        bullets: [
          "Prywatna edycja dowolnego kursu",
          "Autorskie materiały pod Twój stack",
          "Zdalnie albo on-site, PL/EN",
          "Wiele grup, NDA, zamówienie, rejestracja dostawcy",
        ],
        cta: "Ustalmy zakres w 20 minut",
      },
    },
  },
  schedule: {
    eyebrow: "Najbliższe otwarte terminy",
    title: "Konkretne terminy, małe grupy.",
    columns: { course: "Kurs", dates: "Termin", hours: "Godziny", language: "Język", status: "Status", action: "" },
    hoursValue: "09:00–17:00 CET/CEST",
    status: {
      open: "Otwarty",
      filling: "Zapełnia się",
      full: "Brak miejsc",
      confirmed: "Potwierdzony",
      cancelled: "Odwołany",
    },
    languages: { en: "angielski", pl: "polski" },
    seatsLeft: "Wolne miejsca: {n}",
    rowCta: "Zarezerwuj miejsce",
    empty: {
      title: "Pierwsze otwarte terminy są w przygotowaniu.",
      body: "Napisz, który kurs Cię interesuje, a powiadomię Cię jako pierwszego. Albo zamów prywatną edycję.",
      notify: "Powiadom mnie",
      privateRun: "Zamów prywatną edycję",
    },
  },
  catalog: {
    eyebrow: "Katalog, etap 1",
    title: "Trzy ścieżki, jeden standard materiałów.",
    footer:
      "Ścieżki Power BI, Microsoft 365 i Data Engineering w drodze. Potrzebujesz już teraz? Zapytaj, zwykle to kwestia prywatnej edycji.",
    dayOne: "1 dzień",
    dayMany: "{n} dni",
    cardCta: "Zobacz kurs",
  },
  badges: {
    condensed: "Wersja skrócona, 2 dni",
    official: "Oficjalny kurs Microsoft",
    custom: "Autorski program Ludwika",
  },
  levels: { beginner: "Podstawowy", intermediate: "Średniozaawansowany", advanced: "Zaawansowany" },
  whyMe: {
    eyebrow: "Dlaczego ja",
    title: "Większość trenerów czyta courseware. Ja go pisałem.",
    headers: { them: "Typowy trener Microsoft", me: "Ludwik" },
    rows: [
      { them: "Czyta oficjalny courseware", me: "Pisał autorskie programy szkoleniowe dla NATO" },
      { them: "Uczy funkcji", me: "Uczy systemów, które przetrwają produkcję" },
      {
        them: "Zna bieżącą wersję",
        me: `Od ${proof.yearsMct} lat szkoli z każdej generacji platformy danych Microsoft`,
      },
      { them: "Prowadzi zajęcia w labie", me: "Doradzał firmom z Fortune 500 i organizacjom wojskowym" },
      {
        them: "Mówi jednym językiem do jednej grupy",
        me: "Tego samego dnia przechodzi od głębokiego T-SQL do strategii na poziomie zarządu",
      },
    ],
  },
  proof: {
    eyebrow: "Z ankiet poszkoleniowych",
    title: "Cytaty z ankiet poszkoleniowych: {n}. Zero scenariusza.",
    sub: "Każdy cytat pochodzi z ankiety wypełnionej po szkoleniu. Nie ma tu gwiazdek, bo nie mam jeszcze zbioru ocen liczbowych. Kiedy go zbiorę, zobaczysz wynik i liczbę odpowiedzi.",
    note: "Oryginały po angielsku.",
    filters: {
      all: "Wszystkie",
      military: "Wojsko",
      enterprise: "Enterprise",
      data: "Dane",
      modernwork: "Modern Work",
    },
    readAll: "Pokaż wszystkie ({n})",
    showFewer: "Pokaż mniej",
    empty: "Pod tym filtrem nie ma jeszcze cytatów.",
  },
  process: {
    eyebrow: "Jak to działa",
    title: "Co dzieje się po kliknięciu.",
    lanes: {
      public: {
        title: "Otwarta klasa",
        beats: [
          "Rezerwujesz miejsca (2 min)",
          "Potwierdzam termin i w ciągu 1 dnia roboczego wysyłam pro formę albo fakturę",
          "Przed kursem: dostęp do labu, wymagania wstępne, Twoje pytania",
          "Szkolenie, materiały i 30 dni pytań mailem",
        ],
      },
      briefing: {
        title: "Briefing",
        beats: [
          "Wybierasz temat i 2–3 okna czasowe",
          "Potwierdzam termin i wysyłam jednostronicową notatkę przygotowawczą",
          "3 godziny, Twoje liczby na stole",
          "Pisemne podsumowanie w ciągu 48 h",
        ],
      },
      enterprise: {
        title: "Enterprise",
        beats: [
          "Opisujesz stack i harmonogram (2 min)",
          "20 minut rozmowy o zakresie, bez pitchu",
          "Program szyty na miarę",
          "Szkolenie, które zostaje w zespole: zdalnie albo on-site, po polsku albo po angielsku",
        ],
      },
    },
  },
  faq: { eyebrow: "FAQ", title: "Pytania, które padają przed rezerwacją." },
  finalCta: {
    title: "Kolejne szkolenie ma zmienić to, co Twój zespół wdraża.",
    sub: "Wybierz miejsce, zamów briefing albo ustalmy zakres programu. Odpowiadam w jeden dzień roboczy, a jeśli nie jestem właściwą osobą, powiem to wprost.",
    contactLine: "Wolisz maila? {email}",
  },
  footer: {
    since: "Microsoft Certified Trainer od 2007",
    catalog: "Kursy",
    formats: "Formy współpracy",
    contact: "Kontakt",
    responseTime: "Odpowiadam w ciągu jednego dnia roboczego.",
    privacy: "Polityka prywatności",
    updated: "Treść zaktualizowana {date}",
  },
  form: {
    eyebrow: "Zapytanie",
    modes: { seat: "Otwarta klasa", briefing: "Briefing", scope: "Program na zamówienie" },
    titles: { seat: "Zarezerwuj miejsca", briefing: "Zamów briefing", scope: "Ustalmy zakres" },
    labels: {
      name: "Imię i nazwisko",
      email: "Służbowy e-mail",
      company: "Firma",
      phone: "Telefon (opcjonalnie)",
      course: "Kurs",
      session: "Termin",
      sessionNotify: "Powiadom mnie o następnym terminie",
      seats: "Liczba miejsc",
      language: "Język szkolenia",
      topic: "Temat",
      windows: "Preferowane okna czasowe (2–3)",
      leaders: "Liczba osób z zarządu",
      stack: "Stack",
      teamSize: "Wielkość zespołu i role",
      timeline: "Harmonogram",
      delivery: "Forma",
      procurement: "Wymogi zakupowe",
      message: "Uwagi",
      consent: "Zgadzam się na kontakt w sprawie tego zapytania. Obowiązuje polityka prywatności.",
      wantsPrivateQuote: "Wyceń też prywatną edycję",
    },
    placeholders: {
      briefingMessage: "Jaką decyzję ma odblokować ten briefing?",
      windows: "np. wtorek rano, czwartek po 14:00",
      teamSize: "np. 12 osób: 8 analityków, 4 inżynierów",
      timeline: "np. start Fabric w przyszłym kwartale",
      procurement: "PO, NDA, portal dostawców, termin płatności…",
      message: "Coś, o czym powinienem wiedzieć, zanim odpowiem?",
    },
    options: {
      topicCustom: "Własne pytanie",
      stack: {
        copilot: "Copilot i AI",
        fabric: "Microsoft Fabric",
        sql: "Azure SQL",
        powerbi: "Power BI",
        m365: "Microsoft 365",
        other: "Inne",
      },
      delivery: { remote: "Zdalnie", onsite: "On-site", hybrid: "Hybrydowo" },
      languages: { en: "angielski", pl: "polski" },
    },
    quote: {
      line: "{n} × {price}",
      discount: "Rabat za kilka miejsc −{percent}%",
      total: "Razem netto",
      addSeat: "Dodaj miejsce",
      removeSeat: "Usuń miejsce",
    },
    submit: { seat: "Zarezerwuj miejsca", briefing: "Zamów briefing", scope: "Wyślij i wybierz termin rozmowy" },
    sending: "Wysyłam…",
    microcopy: {
      seat: "Teraz nic nie płacisz. Potwierdzenie dostajesz w ciągu jednego dnia roboczego, a fakturę albo pro formę, gdy termin zostanie potwierdzony.",
    },
    seatsHint6: "Sześć osób lub więcej? Prywatna edycja może wyjść taniej. Zaznacz, a dostaniesz obie wyceny.",
    success: {
      title: "Dzięki, dotarło.",
      body: {
        seat: "Gdy termin zostanie potwierdzony, wyślę fakturę albo pro formę i checklistę przed kursem.",
        briefing: "Zaproponuję termin z Twoich okien czasowych i wyślę jednostronicową notatkę przygotowawczą.",
        scope: "Wybierz poniżej 20-minutowy termin albo poczekaj na mojego maila z trzema pytaniami, dzięki którym rozmowa będzie konkretna.",
      },
      calendar: "Wybierz 20-minutowy termin",
    },
    error: "Coś poszło nie tak. Twoje odpowiedzi są nadal tutaj. Spróbuj ponownie albo napisz na {email}.",
    apiErrors: {
      sessionUnavailable: "Ten termin właśnie się zapełnił albo nie jest już dostępny. Wybierz inny termin lub opcję „Powiadom mnie”.",
      rateLimited: "Zbyt wiele zgłoszeń z tej sieci. Spróbuj ponownie za kilka minut albo napisz na {email}.",
    },
    errors: {
      required: "To pole jest wymagane.",
      email: "Podaj poprawny służbowy e-mail.",
      consent: "Potwierdź zgodę na kontakt.",
      range: "Wpisz liczbę całkowitą od {min} do {max}.",
      tooShort: "Za krótkie.",
    },
  },
  sticky: {
    teams: { label: "Miejsca od {perDay} netto", cta: "Zarezerwuj miejsce" },
    enterprise: { label: "Wdrażasz Fabric albo Copilota?", cta: "Ustalmy zakres w 20 minut" },
    course: { label: "{code} · najbliższy termin {date}", cta: "Zarezerwuj miejsce" },
    courseNoDate: { label: "{code}", cta: "Zamów prywatną edycję" },
    briefing: { label: "3 godziny, do 10 osób z zarządu, {flat} netto", cta: "Zamów briefing" },
    enterprisePage: { label: "20 minut o zakresie, bez pitchu", cta: "Wybierz termin" },
    dismiss: "Zamknij",
  },
  course: {
    duration: "Czas trwania",
    level: "Poziom",
    maxSeats: "Maks. 8 osób",
    liveOnline: "Na żywo online",
    perSeat: "za miejsce",
    orPrivate: "albo prywatna edycja dla Twojego zespołu",
    condensedNotice:
      "Wersja skrócona do 2 dni. W szybkim tempie przerabiamy rdzeń oficjalnego programu: to, co liczy się na egzaminie. Potrzebujesz każdego modułu? Zapytaj o prywatną edycję w pełnym wymiarze.",
    audience: "Dla kogo",
    notFor: "Nie dla",
    outcomesOne: "Po jednym dniu Twój zespół potrafi:",
    outcomes: "Po {n} dniach Twój zespół potrafi:",
    agenda: "Agenda",
    day: "Dzień {n}",
    addOn: "Dodatek od Ludwika",
    prerequisites: "Wymagania wstępne",
    msLearn: "Oficjalny program na Microsoft Learn",
    exam: "Egzamin {code}",
    format: {
      title: "Forma",
      items: [
        "Na żywo online, 09:00–17:00 CET/CEST",
        "Maks. 8 uczestników",
        "Ćwiczenia praktyczne (laby) w Twoim środowisku",
        "Slajdy i pliki do laboratoriów zostają u Ciebie",
        "30 dni pytań mailem po szkoleniu",
      ],
      recording: policies.recording.pl,
    },
    datesTitle: "Terminy tego kursu",
    trainer: {
      eyebrow: "Prowadzący",
      name: "Ludwik C. Siadlak",
      years: "lat jako MCT",
      trained: "przeszkolonych specjalistów",
      countries: "krajów",
    },
    related: "Powiązane kursy",
  },
  briefing: {
    eyebrow: "Briefing dla zarządu",
    title: "Trzy godziny. Jedna decyzja odblokowana.",
    sub: "{flat} netto. 3 godziny zdalnie, do 10 osób z zarządu, pisemne podsumowanie w 48 h.",
    cta: "Zamów briefing",
    topicsEyebrow: "Wybierz jeden temat",
    topicsTitle: "Trzy tematy. Jedna decyzja na każdy.",
    outcomesLabel: "Z czym wychodzisz",
    agendaLabel: "Agenda na 3 godziny",
    topics: {
      a: {
        title: "Copilot: ROI bez marketingu",
        outcomes: [
          "Mapa procesów: gdzie Copilot realnie pomaga, a gdzie nie",
          "Decyzja licencyjna, którą obronisz",
          "Projekt 90-dniowego pilotażu z metrykami",
        ],
        agenda: [
          { time: "0:00–0:30", item: "Co Copilot naprawdę robi w M365 (na żywo, nie na slajdach)" },
          { time: "0:30–1:15", item: "Pięć Twoich procesów-kandydatów: oszczędność czasu kontra ryzyko" },
          { time: "1:15–1:30", item: "Przerwa" },
          {
            time: "1:30–2:15",
            item: "Licencje, ekspozycja danych i warunki governance (etykiety poufności, oversharing)",
          },
          { time: "2:15–2:45", item: "Projekt pilotażu: grupa, metryki, kryteria wyjścia" },
          { time: "2:45–3:00", item: "Decyzje i właściciele" },
        ],
      },
      b: {
        title: "Fabric: budować czy kupować",
        outcomes: [
          "Jasne stanowisko: Fabric kontra Twój obecny stack (Synapse, Databricks, Snowflake, SQL on-prem)",
          "Model pojemności i kosztów",
          "Kolejność migracji",
        ],
        agenda: [
          { time: "0:00–0:20", item: "Twoje obecne środowisko na jednym slajdzie (Twoim)" },
          { time: "0:20–1:00", item: "Architektura Fabric w 40 minut" },
          { time: "1:00–1:45", item: "Model pojemności i koszt F-SKU przy Twoich wolumenach" },
          { time: "1:45–2:25", item: "Co przenieść najpierw, a czego nie ruszać nigdy" },
          { time: "2:25–2:45", item: "Luka kompetencyjna i kolejność szkoleń" },
          { time: "2:45–3:00", item: "Decyzje" },
        ],
      },
      c: {
        title: "Governance AI w organizacji regulowanej",
        outcomes: [
          "Model governance, który przejdzie audyt i nie zamrozi wdrożenia",
          "Decyzja o granicach danych",
          "Checklista odpowiedzialnego AI z imiennymi właścicielami",
        ],
        agenda: [
          { time: "0:00–0:30", item: "Model zagrożeń dla generatywnego AI w Twoim kontekście" },
          {
            time: "0:30–1:15",
            item: "Mechanizmy kontroli Microsoft: Purview, DLP, grounding w tenancie, governance agentów",
          },
          { time: "1:15–1:45", item: "Szkielet polityki" },
          { time: "1:45–2:15", item: "Plan reagowania na incydenty" },
          { time: "2:15–2:45", item: "Proces zatwierdzania nowych agentów" },
          { time: "2:45–3:00", item: "Decyzje" },
        ],
      },
    },
    ownQuestion: "Masz własne pytanie? Ten sam format, ta sama cena.",
  },
  enterprise: {
    eyebrow: "Enterprise i sektor publiczny",
    title: "Programy pod Twój stack, Twoje wdrożenie, Twój termin.",
    sub: "To nie otwarty kurs z Twoim logo na slajdach. Zaczynam od Twojego stacku, terminu wdrożenia i ról w sali, potem składam program z oficjalnego courseware Microsoft, własnych materiałów i Twoich systemów. Jedna grupa albo dwanaście, zdalnie albo on-site, po polsku albo po angielsku. Dokument programu dostajesz przed fakturą.",
    primaryCta: "Ustalmy zakres w 20 minut",
    secondaryCta: "Wybierz termin rozmowy",
    casesEyebrow: "Gdzie to już działało",
    casesTitle: "Sale, w których uczyłem.",
    cases: [
      { id: "nato", title: "NATO", body: "Autorskie programy szkoleniowe. Pisane, nie czytane." },
      { id: "us-army", title: "US Army Europe / USARAF", body: "Tygodniowe kursy techniczne w Wiesbaden i Vicenzy." },
      { id: "banking", title: "Nordea, ING, DNB", body: "Szkolenia z platform danych dla zespołów bankowych." },
      { id: "manufacturing", title: "Volvo, Scania, Volkswagen", body: "Zespoły danych w przemyśle." },
    ],
    procurement: {
      eyebrow: "Zakupy",
      title: "Formalności biorę na siebie.",
      facts: [
        {
          label: "VAT",
          body: "Ceny są netto. Firmy z UE z ważnym numerem VAT UE: odwrotne obciążenie. Firmy z Polski: +23% VAT.",
        },
        { label: "Zamówienia (PO)", body: "Podaj numer PO, a trafi na fakturę." },
        { label: "NDA", body: "Twoje albo moje, podpisane przed rozmową o zakresie, jeśli tego potrzebujesz." },
        { label: "Rejestracja dostawcy", body: "Formularze dostawcy wypełniam ja. Ty je tylko wysyłasz." },
        { label: "Płatność", body: policies.paymentTerms.pl },
        { label: "Rezygnacja", body: policies.cancellationPrivate.pl },
      ],
    },
    privateRun: {
      title: "Prywatne edycje",
      body: "Prywatne edycje wyceniam za dzień szkoleniowy, nie za osobę. Dla całego zespołu to zwykle lepszy układ, a obie kwoty pokazuję Ci obok siebie.",
    },
  },
} satisfies MctCopy;
