// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgavdhdgxzijbmhyblxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnYXZkaGRneHppamJtaHlibHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Nzk0MDQsImV4cCI6MjA2MDE1NTQwNH0.C3l-wgJWTd6s1L6urUOwvsnFlL8cWe7VaGDA7mjBOLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);